#!/bin/bash
# scripts/init_workspace.sh
# Running as non-root user (ros) within the container or WSL

set -e

# --- Config ---
WS_DIR=~/ros_ws
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
CONFIG_DIR="$SCRIPT_DIR/../config"
LOG_PREFIX="[RX-Workspace]"

log() { echo -e "\033[0;32m$LOG_PREFIX $1\033[0m"; }

# Detect shell and warn/switch if necessary
if [ -z "$BASH_VERSION" ]; then
    log "WARNING: Running in $0 (likely sh). Switching to bash is recommended for full feature support."
    # We can't easily auto-switch the parent process, but we can warn.
fi

# Ensure .bashrc acts as config source
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# --- Helpers ---

inject_bashrc() {
    local block_name="ROS2_ENV_BLOCK"
    local start_marker="# --- $block_name START ---"
    local end_marker="# --- $block_name END ---"

    # Check if block exists, if so delete it (to update it)
    if grep -q "$start_marker" ~/.bashrc; then
        sed -i "/$start_marker/,/$end_marker/d" ~/.bashrc
    fi

    log "Updating .bashrc configuration..."

    cat <<EOF >> ~/.bashrc
$start_marker
# Auto-generated by init_workspace.sh
# Ensure we use the Native Docker Engine (not Docker Desktop)
export DOCKER_HOST=unix:///var/run/docker.sock

if [ -f "$CONFIG_DIR/aliases.sh" ]; then
    source "$CONFIG_DIR/aliases.sh"
fi

if [ -f "$WS_DIR/install/setup.bash" ]; then
    source "$WS_DIR/install/setup.bash"
fi

# Auto-navigate to workspace
cd $WS_DIR
$end_marker
EOF
}

setup_terminator() {
    local config_src="$CONFIG_DIR/terminator_config"
    local config_dest="$HOME/.config/terminator/config"

    if [ ! -f "$config_src" ]; then
        log "Terminator config source not found. Skipping."
        return
    fi

    mkdir -p "$(dirname "$config_dest")"

    # Symlink if not already linked correctly
    if [ ! -L "$config_dest" ] || [ "$(readlink -f "$config_dest")" != "$(readlink -f "$config_src")" ]; then
        rm -f "$config_dest"
        ln -s "$config_src" "$config_dest"
        log "Linked Terminator config."
    fi
}

init_rosdep() {
    if [ ! -d "/etc/ros/rosdep" ]; then
        log "Initializing rosdep..."
        sudo rosdep init || true
    fi

    if [ ! -f "$HOME/.ros/rosdep/sources.cache/index" ]; then
        log "Updating rosdep database..."
        rosdep update
    fi
}

# --- Main ---

log "Initializing Development Workspace..."

inject_bashrc
setup_terminator
init_rosdep

log "Initialization Complete."
